services:
  db:
    build:
      context: ..
      dockerfile: ./docker/database/Dockerfile
    container_name: vaudoise-db
    environment:
      POSTGRES_DB: Vaudoise
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Vaudoise_Cest_Cool_1410
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    container_name: vaudoise-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Vaudoise
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vaudoise_Cest_Cool_1410
      SPRING_PROFILES_ACTIVE: pd
      JAVA_OPTS: -Xms256m -Xmx512m
    ports:
      - "8080:8080"

volumes:
  db_data: {}
